### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by Raizelian** [brearlycoffee/scuolabook-dl-ffh#1]
Sistema operativo: macOS Mojave 10.14.6 con Python 3, Firefox 78.0.2 e Geckodriver 0.26.0.

Dopo l'inserimento del book ID e la creazione della cartella, ricevo due errori TimeoutException; nel dettaglio:

```
Traceback (most recent call last):
  File "path/scuolabook-dl-ffh-master/sbdownloader.py", line 163, in <module>
    img = WebDriverWait(driver,5).until(EC.presence_of_element_located((By.CSS_SELECTOR, imgselector)))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path/scuolabook-dl-ffh-master/sbdownloader.py", line 166, in <module>
    img = WebDriverWait(driver,5).until(EC.presence_of_element_located((By.CSS_SELECTOR, imgselector)))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by StefanoGiu** [comment]
Problem is with "img:nth-child(2)"... child can go from 2 to 5... if you will fix this, it will work properly ;)

**Comment by Raizelian** [comment]
> Problem is with "img:nth-child(2)"... child can go from 2 to 5... if you will fix this, it will work properly ;)

I'm sorry, I don't think I get it. It's a CSS thing, right?, but I don't see how that could help.

Furthermore, I'm actually seeing that the book I want to download is _320 pages long_ (if you open it up and check manually) but the website says _420_, so that's where the webdriver gets stuck, I guess.
Problem is, I don't know how to set a custom number of pages, or how to manually input 320 in the code so that it stops at that number of pages in any case.
It would be interesting to test this with a book that has the same number of pages both in its description and in actuality.

Can you offer further help?

EDIT: I did manage to make it stop to a custom number of pages, but unfortunately now I get a **"TypeError: a bytes-like object is required, not 'str'"** error whenever all the pages are done downloading and the script tries to generate a pdf.
Still, I got all the pages from the book and I can easily merge them into a pdf on my own, but it would be cool anyway at this point to figure out how to make this work properly.

Reading around, it's possibly a matter regarding python3 as opposed to python2 where the "bytes" type object wasn't a thing, I think.
